menu:
  main:
    - name: Home
      weight: 1
      pageRef: /
    - name: Categories
      weight: 2
      pageRef: /categories/
    - name: Cuisines
      weight: 3
      pageRef: /cuisines/
    - name: Tags
      weight: 4
      pageRef: /tags/
    - name: Ingredients
      weight: 5
      pageRef: /ingredients/
    - name: Equipment
      weight: 6
      pageRef: /equipment/
params:
  social_account_types:
    - mastodon
    - github
  social_account_types_params:
    mastodon:
      rel_me: true
      text: Follow me on Mastodon
      logo: fa-mastodon
      link: "https://[0]/@[1]"
      link_values:
        - server
        - username
    github:
      rel_me: false
      text: Source on GitHub
      logo: fa-github
      link: "https://github.com/[0]/[1]"
      link_values:
        - username
        - repository
  cookbook_credits: "[Cookbook Theme](https://github.com/mwtaylor/CookbookHugoTheme) created by [mwtaylor](https://github.com/mwtaylor)"
